### ISSUE TITLE
Both methods for HOTP or TOTP code generation generates the same result

### ISSUE THREAD

**Issue by OttoChamo** [Daegalus/dart-otp#10]
Is it an expected behavior that both methods for OTP generation keep generating the same value even when we set a time interval?

**Comment by amadejkastelic** [comment]
Time parameter is in ms, interval parameter is in seconds. You're probably passing in the wrong value for time or just not waiting long enough, because code stays the same for 30 seconds in your case. Try to pass in `DateTime.now().millisecondsSinceEpoch` and set interval to 1 second.

- 30 seconds = 30000 milliseconds
- 1 second = 1000 milliseconds

**Comment by Daegalus** [comment]
Well, if you pass 0, they will both return the same number. for HOTP tokens, you have to increment the value yourself every time, otherwise it will just keep generating the same number. the "time" and "count" parameters for TOTP and HOTP respectively are the seeds to the random number generator. If you pass in the same seed, you get the same result.

The only difference between TOTP and HOTP is that you use Time as the seed for TOTP, and I divide time by the interval (which defaults to 30 seconds). this is so that we get the same code for the whole 30 second slot. 

If you set the Interval to 1 for TOTP and pass time into both functions, they will always be the same. 

if you pass a time of `3` to TOTP and a count of `3` to HOTP (aka, the same seed), you should get different results, because the TOTP is divided by 1000 (to convert from milliseconds to seconds), then divided by the interval (default is 30), then floor(), which results in 0. while the HOTP will stay 3. which should give you 2 different codes.

`30000` (30 seconds) for TOTP with default interval and `1` for HOTP will also give the same result.

since all the options are optional and have sane defaults, you can just do 

```
int otpGenerated() {
    return OTP.generateTOTPCode("aRandOMSECRET", DateTime.now().millisecondsSinceEpoch)
}
```

To generate a new OTP every 30 seconds. If you need to generate 30 seconds before, and 30 seconds after for safety or server-side checking. you can just do `DateTime.now().millisecondsSinceEpoch-30000` and `DateTime.now().millisecondsSinceEpoch+30000` accordingly in your code if you ever need that.

But since this looks like a Flutter app, and is client side, you only need the current code.

I hope this helps.

**Comment by Daegalus** [comment]
Havent heard a response in a while, I closing this. If its still an issue, please reopen.
