### ISSUE TITLE
Function to access the interval

### ISSUE THREAD

**Issue by guilhermedaldim** [Daegalus/dart-otp#32]
@Daegalus nice work with the plugin, it's really good!

That's not a issue, I'd like support for accessing the interval between changing one code to another.

I tried to create a timer to show the code expiry time, however, the plugin starts counting before the layout, so my timer is not accurate.

**Comment by Daegalus** [comment]
I can try to do that, but my library doesn't do any actual counting. For TOTP it just takes the current time, divided by the provided interval (to 30 by default for 30 seconds) and uses that as the number passed to HOTP. This makes it so that the number changes only at your intervals. But it never counts.

For HOTP, it relies on the user to do the counting.

I can expose the value of the current TOTP interval time value if that helps any, so you could pass it into HOTP if needed. 

Would that help? If so I can probably add it sometime this week.

**Comment by guilhermedaldim** [comment]
I'm using TOTP, exposing the interval value would help, so I would be able to create my timer according to the plugin's interval, which would be a great help.

**Comment by Daegalus** [comment]
Ok, give me a few days to get this added in a clean manner and I'll report back.

**Comment by Daegalus** [comment]
Ok, just released 3.0.1 with 2 new static variables you can check for information.

```dart
OTP.lastUsedTime
OTP.lastUsedCounter
```

`lastUsedTime` is just the timestamp. It should be identical to whatever is passed into the function.
`lastUsedCounter` will be the modified timestamp that is divided by the interval you provide (in this case 30 seconds). This is the one that will probably most useful for you.

If you use `lastUsedCounter` to generate a code, remember to pass it into generateHOTP, as generateTOTP will try to think of it as a unix timestamp and do all the math magic on it again. Hope this helps.

I will close this ticket, reopen it or start a new one if you have any issues.
